**ndarray：一种多维数组对象**
* 一个通用的同构数据多维容器
* 所有元素必须是相同类型的
* 每个数组都有一个shape(一个表示各维度大小的元组)和dtype（一个用于说明数组数据类型的对象）

In [25]:
import numpy as np
data = np.array([[0.9526,-0.246,-0.8856],
        [0.5639,0.2379,0.9104]])

In [27]:
data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [28]:
data * 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [29]:
data + data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [30]:
data.shape

(2, 3)

In [31]:
data.dtype

dtype('float64')

** 创建ndarray **

创建数组最简单的办法就是使用array函数，它接受一切序列型的对象（包括其他数组），然后产生一个新的含有传入数据的NumPy数组。



In [32]:
data1 = [6,7.5,8,0,1]

In [33]:
arr1 = np.array(data1)

In [34]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [37]:
# 嵌套序列（一组等长序列组成的列表）将会被转换为一个多维数组
data2 = [[1,2,3,4],[5,6,7,8]]

In [39]:
arr2 = np.array(data2)

In [42]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
arr2.ndim

2

In [44]:
arr2.shape

(2, 4)

除非显示说明，np.array会尝试为新建的数组推断出一个较为合适的数据类型，，保存在一个特殊的dtype对象中。 

In [45]:
arr1.dtype

dtype('float64')

In [46]:
arr2.dtype

dtype('int32')

In [47]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [48]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [54]:
np.empty([2,3,2])

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [55]:
# arange是Python内置函数range的数组版
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**ndarray的数据类型**
* dtype是一个特殊的对象，它含有ndarray将一块内存解释为特定数据类型所需的信息。
* 通过astype方法显示地转换为dtype

In [56]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [60]:
arr2 = np.array([1,2,3],dtype=np.int32)

In [61]:
arr1.dtype

dtype('float64')

In [62]:
arr2.dtype

dtype('int32')

In [63]:
arr = np.array([1,2,3,4,5])

In [64]:
arr.dtype

dtype('int32')

In [67]:
# 整数被转换成了浮点数，如果浮点数转换成整数，则小数部分将会被截断。
float_arr = arr.astype(np.float64)

In [68]:
float_arr.dtype

dtype('float64')

In [69]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [70]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [71]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [72]:
# 如果某些字符串数组表示的全是数字，也可以用astype将其转换为数值形式
numeric_strings = np.array(['1.25','-9.6','42'],dtype=np.string_)

In [73]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [78]:
int_array = np.arange(10)

In [79]:
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)

In [80]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [81]:
empty_unit32 = np.empty(8,dtype='u4')

In [82]:
empty_unit32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)