### 概况
* 基于 NumPy构建的

#### 数据结构
* *Series*：一种类似于一维数组的对象，它由一组数据（各种NumPy数据类型）以及一组与之相关的数据标签（即索引）组成。
* DataFrame

In [1]:
from pandas import Series,DataFrame
import pandas as pd
import numpy as np

In [2]:
obj = Series([4,7,-5,3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
# 创建带有一个可以对各个数据点进行标记的索引

obj2 = Series(data=[4,7,-5,3],index=['d','b','a','c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [10]:
obj2['d'] = 6

In [11]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
# 可以将Series看成是一个定长的有序字典，因为它是索引值到数据值的一个映射。

'b' in obj2

True

In [18]:
'e' in obj2

False

In [19]:
# 如果数据被存放在一个Python字典中，也可以直接通过这个字典来创建Series

sdata = {"Ohio":35000,'Texas':71000,'Oregon':1,'Utah':5000}

In [20]:
obj3 = Series(sdata)

In [21]:
obj3

Ohio      35000
Oregon        1
Texas     71000
Utah       5000
dtype: int64

In [22]:
states = ['California','Ohio','Oregon','Texas']

In [23]:
obj4 = Series(sdata,index=states)

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon            1.0
Texas         71000.0
dtype: float64

In [25]:
# NaN = Not a Number
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3

Ohio      35000
Oregon        1
Texas     71000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon            1.0
Texas         71000.0
dtype: float64

In [30]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon             2.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
obj3

Ohio      35000
Oregon        1
Texas     71000
Utah       5000
dtype: int64

In [32]:
obj4

California        NaN
Ohio          35000.0
Oregon            1.0
Texas         71000.0
dtype: float64

In [33]:
obj3['Utah']

5000

In [34]:
test1 = ['one','two']

In [35]:
test2 = {'one':1000,'two':2000,'three':3000}

In [36]:
test11 = Series(test2)

In [37]:
# 如果传入一个字典，则结果Series中的索引就是原字典的键（有序排列）
test22 = Series(test1)

In [38]:
test11 + test22

one      NaN
three    NaN
two      NaN
0        NaN
1        NaN
dtype: object

In [39]:
test11

one      1000
three    3000
two      2000
dtype: int64

In [40]:
test22

0    one
1    two
dtype: object

In [41]:
# Series  对象本身及其索引都有一个name属性，该属性跟pandas其他的关键功能关系非常密切

obj4.name = 'population'

In [42]:
obj4.index.name = 'state'

In [43]:
obj4

state
California        NaN
Ohio          35000.0
Oregon            1.0
Texas         71000.0
Name: population, dtype: float64

In [44]:
# Series的索引可以通过赋值的方式就地修改

obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

##### DataFrame的介绍
* 一个表格型的数据结构，含有一组有序的列，每列可以是不同的值类型
* 既有行索引，也有列索引，可以被看作是由Series组成的字典（共用同一个索引）

In [45]:
#构建DataFrame最常用的方法就是直接传入一个由等长列表或NumPy数组组成的字典：

data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002],'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(data)

In [46]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [48]:
# 指定列序列之后，则DataFrame的列就会按照指定顺序进行排列
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [51]:
# 如果传入的列在数据中找不到，就会产生NA值
frame2 = DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [52]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [53]:
# 通过类似字典标记的方式或属性的方式，可以将DataFrame的列获取为一个Series
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [54]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [56]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [57]:
# 列可以通过赋值的方式进行修改
frame2['debt'] = 16.5

In [58]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [63]:
frame2['debt'] = np.arange(5.)

In [64]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [65]:
#如果赋值的是一个Series，就会精确匹配DataFrame的索引，所有的空位都将被缺失值填充
val = Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [66]:
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [69]:
# 为不存在的列赋值会创建出一个新列，关键字del用于删除列：
frame2['eastern']=frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [71]:
del frame2['eastern']

In [73]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [77]:
# 如果将嵌套字典传给DataFrame，则外层字典的键将被作为列，内层键将被作为行索引。
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [78]:
frame3 = DataFrame(pop)

In [79]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [80]:
#也可以对结果进行转置
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [81]:
# 内层字典的键会被合并、排序以形成最终的索引，但是显示指定索引不会出现这样的情况

DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [82]:
# 由Series组成的字典方法类似
pdata ={'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:2]}

In [83]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [86]:
frame3.index.name='year'
frame3.columns.name='state'

In [87]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [88]:
# values属性也会以二维ndarray的形式返回DataFrame中的数据
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [89]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

#### 索引对象
* 负责管理轴标签和其他元数据

构建Series或DataFrame时，所用到的任何数组或其他序列的标签都会被转换成一个Index:

In [90]:
obj = Series(range(3),index=['a','b','c'])

In [91]:
index = obj.index

In [92]:
index

Index(['a', 'b', 'c'], dtype='object')

In [93]:
index[1:]

Index(['b', 'c'], dtype='object')

In [94]:
index[0:2:1]

Index(['a', 'b'], dtype='object')

In [100]:
index[0::1]

Index(['a', 'b', 'c'], dtype='object')

In [106]:
# Index对象是不可修改的（immutable）
# index[1]='d'
# 不可修改性使得Index对象在多个数据结构之间安全共享：
index = pd.Index(np.arange(3))
obj2 = Series([1.5,-2.5,0], index = index)

In [107]:
obj2.index is index

True

In [108]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [109]:
'Ohio' in frame3.columns

True

In [110]:
2003 in frame3.index

False

#### Series和DataFrame基本功能

In [111]:
# 重新索引
obj = Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [112]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [115]:
# reindex将会重新排列，如果索引值不在，就引入缺失值
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [116]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [117]:
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])

In [121]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [125]:
#对于DataFrame，reindex可以修改（行）索引、列、或两个都修改，仅传入一个序列，则会重新索引行
frame = DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],
                  columns = ['Ohio','Texas','California'])

In [123]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [126]:
frame2 = frame.reindex(['a','b','c','d'])

In [127]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [128]:
# 使用columns关键字即可重新索引列：
states = ['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [133]:
#也可同时对行和列进行重新索引，而插值智能按行应用（即轴0）
# frame.reindex(index=['a','b','c','d'],method='ffill',columns = states)
frame.ix[['a','b','c','d'],states]

G:\Program Files\Anaconda\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  This is separate from the ipykernel package so we can avoid doing imports until


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [134]:
obj = Series(np.arange(5.),index=['a','b','c','d','e'])

In [136]:
# drop方法返回的是一个在指定轴上删除了指定值的新对象
new_obj = obj.drop('c')

In [137]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [138]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [139]:
# 对于DataFrame，可以删除任意轴上的索引值：
data = DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])

In [140]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [142]:
data.drop(['one','two'],axis=1)

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

#### 索引、选取和过滤

In [143]:
obj = Series(np.arange(4.),index=['a','b','c','d'])

In [144]:
obj['b']

1.0

In [145]:
obj[1]

1.0

In [146]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [147]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [148]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [152]:
# 对标签的切片运算与普通的切片运算不同，其末端是包含的
obj['b':'c']

b    5.0
c    5.0
dtype: float64

In [153]:
obj['b':'c'] = 5

In [154]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [157]:
data = DataFrame(np.arange(16).reshape((4,4)),
                 index = ['Ohio','Colorado','Utah','New York'],
                 columns = ['one','two','three','four'])

In [158]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [159]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [160]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [161]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [162]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [163]:
# 通过布尔型DataFrame进行索引
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [164]:
data[data<5]=0

In [165]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [171]:
# 索引字段ix，可以通过NumPy式的标记法以及轴标签从DataFrame中选取行和列的子集

data.ix['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [172]:
data.ix[['Colorado','Utah'],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [173]:
data.ix[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [174]:
data.ix[data.three>5,:3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14